on: 
  push:
   branches:
    - main
name: ðŸš€ Deploy REST API
jobs:
      web-deploy:
        name: ðŸŽ‰ Deploy REST API
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [22.x]
        steps:
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
          - name: ðŸ“‚ Deploy to Cloud
            uses: wlixcc/SFTP-Deploy-Action@v1.2.4
            with:
              sftpArgs: '-o ConnectTimeout=5'
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              remote_path: '/var/www/backend'
              sftp_only: true
              local_path: './'
        


   
             
